version: '3.8'
services:
  piclo_db:
    image: postgres:13-alpine3.17
    container_name: piclo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: picloapp
    volumes:
      - ../piclo_data:/var/lib/postgresql/data
    networks:
      - piclo_network
    ports:
      - 5432:5432

  picloAPI_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picloAPI_app
    volumes:
      - .:/code
    restart: always
    depends_on:
      - piclo_db
    networks:
      - piclo_network
    ports:
      - 8000:8000

networks:
  piclo_network:
    driver: bridge